NIUANULP/nulp-elite-ui

packages/nulp_elite/src/pages/SampleTest.js
- Used material UI to show dropdown
- Show user preference popup using static data.
=> Task#212474: Show user preference popup using static data

packages/common-lib/src/services/RestClient.ts, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/Contents.js
=> Task #215071 frontend cookie session issue fixed and added URL config file

packages/nulp_elite/src/pages/Courses.js
=> Header changes

packages/nulp_elite/src/pages/tenantService.js
=> TASK: [#215408] :Added Tenant service

packages/nulp_elite/src/App.js, packages/nulp_elite/src/configs/appConfig.json, packages/nulp_elite/src/pages/CourseTest.js, packages/nulp_elite/src/services/courseService.js
=> TASK: [#215263] :Updated course service

.github/workflows/build-test.yml, module-template/public/index.html, packages/common-lib/src/components/SearchLayout.js, packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/Contents.js, packages/nulp_elite/src/pages/Courses.js, packages/nulp_elite/src/pages/FAQData.json, packages/nulp_elite/src/pages/FAQPage.js, packages/nulp_elite/src/pages/Frmework.js, packages/nulp_elite/src/pages/Profile.js, packages/nulp_elite/src/pages/User.js, packages/nulp_elite/src/pages/UserPrefPopup.js
=> sidebar menu, language menu, footer changes, design changes

packages/nulp_elite/src/services/chennelService.js, packages/nulp_elite/src/services/contentService.js, packages/nulp_elite/src/services/dataService.js, packages/nulp_elite/src/services/formService.js, packages/nulp_elite/src/services/frameworkService.js, packages/nulp_elite/src/services/learnerService.js, packages/nulp_elite/src/services/playerService.js, packages/nulp_elite/src/services/tenantService.js
=> Task #215582 feat: [BE] Moving services to the nulp_elite service package

packages/common-lib/src/components/layout/Footer.js, packages/common-lib/src/components/layout/Layout.js, packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #216462 ,Task #216464 - design for footer and header

packages/nulp_elite/src/pages/search/DomainList.js
=> domain to content list

packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #0000: API integration- conflicts

packages/nulp_elite/src/components/search.js, packages/nulp_elite/src/pages/Contents.js
=> Task : #216126 Content search API integration

scripts/pack-prod-build.sh
Need to add these variables later if the solution found
`<input type=\"hidden\" id=\"p1reCaptchaEnabled\" value=\"true\" />\
<input type=\"hidden\" id=\"p1reCaptchaEnabled\" value=\"false\" />\
<input type=\"hidden\" id=\"p2reCaptchaEnabled\" value=\"true\" />\
<input type=\"hidden\" id=\"p2reCaptchaEnabled\" value=\"false\" />\
<input type=\"hidden\" id=\"p3reCaptchaEnabled\" value=\"true\" />\
<input type=\"hidden\" id=\"p3reCaptchaEnabled\" value=\"false\" />\`
Adding HTML tags in index.ejs after build.
=> TASK #216734 Adding variables Html to index.html after build

packages/nulp_elite/src/pages/profile/Profile.js
=> Task #0000 - Profile ui

packages/nulp_elite/src/components/filter.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/services/contentService.js
=> Task #216406 : Add filter dropdown and API call of contentList

packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #0000 - domain carousel

packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/services/utilService.js
=> TASK : #216809 API integration on profile page

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/assets/learningHistory.json, packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #0000 profile page - learning history

packages/nulp_elite/src/pages/profile/certificate.js
=> Task #216914 : Certificate page API call

package.json
=> #0000 - ADD react multi carousel in package file

packages/nulp_elite/src/pages/profile/learningHistory.js
=> Task #216919 : API call on Learning History page

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/components/header.js
=> Task #0000 - UI for header footer links update

packages/nulp_elite/src/pages/content/AllContent.js
=> Task #0000: Removed commented code

packages/nulp_elite/src/pages/connections/AddConnections.js
=> Task#0000-direct connect changes

packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/search/ContentList.js
=> Task #217140 : content detail Page API integration

packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/components/search.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI for language change, back

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/certificate.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js
=> Task #217020: profile page routing and continue learning page API call

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI for adding back buttn in view allpage

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/content/noResultFound.js, packages/nulp_elite/src/pages/content/pdf.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/registration/Registration.js, packages/nulp_elite/src/pages/registration/SendOtp.js, packages/nulp_elite/src/styles/style.css
=> Task #217299 - No data found, profile page changes as per desktop

package.json, packages/nulp_elite/src/App.js, packages/nulp_elite/src/configs/zustandStore.js, packages/nulp_elite/src/pages/registration/Otp.js, packages/nulp_elite/src/pages/registration/Registration.js, yarn.lock
- User registration and OTP form API integration
- Implemented User registration and OTP form API integration
- Added common Zustand store to maintain state-management
- Login existing user from the local env for user start session 
- Fill in the user field and click on the captcha
- Click Continue
- Enter OTP 
- Click Submit
=> TASK #216958: Registration page API integration

packages/nulp_elite/src/components/FloatingChatIcon.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/profile/certificate.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js
=> Task #217368 : Chatbot Integration

packages/nulp_elite/src/App.js, packages/nulp_elite/src/assets/domainImgForm.json, packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/registration/Registrationold.js, packages/nulp_elite/src/pages/registration/SendOtp.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
card changes and demo change requirements
=> card changes and demo change requirements

packages/nulp_elite/src/pages/connections/AddConnections.js
=> show connected, invitation received users and send chat user list on my connection tab

packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/pages/search/ContentList.js
=> Task #217286: Added Search functionality on ContentList Page

packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #217286: Add Search Functionality on DomainList page

packages/nulp_elite/src/pages/connections/AddConnections.js
=> UI changes

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js
=> caraosal selected class

packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/search/ContentList.js
=> pagination changes

packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/registration/Otp.js, packages/nulp_elite/src/pages/terms.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI for terms page in OTP

packages/nulp_elite/src/components/search.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #217691 : show searched text in search box on contentList page

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/message.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - ui-fixes after demo

packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/pages/search/ContentList.js
=> Task #217744 : resolved pagination isuue on contentList page

packages/nulp_elite/src/pages/content/joinCourse.js
=> Task #217804 : removed course breadcrum fronm the courseDetail page

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/message.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/registration/Otp.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - demo ui fixes for profile, direct connect and content detail page

packages/nulp_elite/src/pages/profile/certificate.js
=> Task #217968 : change date format on on Certificate page

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/message.js, packages/nulp_elite/src/pages/registration/Otp.js
=> Task #217937 :API to read chat and show unread message UI

packages/nulp_elite/src/pages/connections/message.js, packages/nulp_elite/src/pages/registration/Otp.js
=> Task #0000: OTP submit  button issue fixed

packages/nulp_elite/src/pages/connections/AddConnections.js
=> resolve conflicts

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI for search box in add connection page

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/pages/FAQPage.js, packages/nulp_elite/src/pages/registration/Registration.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 help page and bug fixes

packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Fixed search page issue

packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #218213 : Join course flow

packages/nulp_elite/src/pages/search/ContentList.js
=> Bug #218356 - search page is not working

packages/nulp_elite/src/configs/designations.json, packages/nulp_elite/src/pages/connections/message.js
=> Task #218507: For one to one chatting sender should get message read and delivered status

packages/nulp_elite/src/pages/connections/AddConnections.js
=> Task #218230: Invitation messages should be visible before accepting the request

packages/nulp_elite/src/pages/content/joinCourse.js
=> ask #218256: user unenroll API call and UI development

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/profile/Profile.js
=> Task #218580 : Filter functionality (by name and by designation)

packages/nulp_elite/src/pages/content/joinCourse.js
=> Task #218447: consent form API integration and form UI

packages/nulp_elite/src/pages/connections/message.js
=> Task #0000: Added validation on block reason field

packages/nulp_elite/src/pages/search/DomainList.js
=> resolved header not found issue on domainList page

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #219039 ,Design - UI for reusable component Header, card, Footer desktop and mobile)

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/message.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #219569 - Design - Resusable filter component 

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js
=> Task #219386 :  [FE] Render the chat page based condition desktop or mobile

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js, packages/nulp_elite/src/styles/style.css
=> Task #219109 - Design - UI for direct connect page (desktop and mobile)

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 UI fixes for card and header active class

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task#0000: Show selected domain name instead of domain code, Task#0000: show result based upon selected domain

packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI fixes after internal demo for join course page

packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js
=> join course breadCrumbs

packages/nulp_elite/src/pages/profile/Profile.js
=> Task #0000: Edit icon not visible in profile page

packages/nulp_elite/src/pages/content/joinCourse.js
=> TASK : Course Module issue fixed

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/pages/profile/Profile.js
=> Task #0000: Fixed translation and profile BIO and designation issue

packages/nulp_elite/src/pages/content/CategoryPage.js
=> Task #220044: On click on view all show result accordingly

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/continueLearning.js
=> Task #220036: On course detail page chat wit creator in desktop view should look like same as direct connect

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/pages/search/ContentList.js
=> Task #219950: Global search functionality

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #220041 - Unit testing and fixes for all pages on mobile all content, content detail page,search landing, search page 

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/profile/learningHistory.js, scripts/pack-prod-build.sh
=> Task #220193 : Write script to copy all files of webapp in dist except index.ejs

packages/nulp_elite/src/App.js, packages/nulp_elite/src/configs/routeConfig.json
=> Task#0000: Add routes in routeConfig.json and removed from app.js

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
Reverts NIUANULP/nulp-elite-ui#200
=> Revert "Task#0000: Route added in components and pages"

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/certificate.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/styles/style.css
=> Task #220526 - UI - feedback changes

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/styles/style.css
=> Task #0000: Development - feedback changes

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI for mobile fixes

packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/connections/AddConnections.js
=> Task #220723: [FE] Initial name of logged in user on profile

packages/nulp_elite/src/pages/connections/AddConnections.js
=> Task #0000: Chat window not opening in mobile

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/styles/style.css
=> Task #220725 - Fixing mobile issues 

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #220828: [FE] Parallel building fix with session Id

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #0000: Added dynamic routes for view all and contentList

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #0000: Update with main branch

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/styles/style.css
=> Task #220725 - Fixing mobile issues

packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
=> event detail API

package.json, packages/nulp_elite/package.json, packages/nulp_elite/src/components/EventCard.js, packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/events/eventList.js, yarn.lock
=> Task #220725 - Fixing mobile issues Task #220889: UI implementation - Webinar List view

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - ui fixes for cards alignment

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/CategoryPage.js
=> Task #220884 : Bug fixes- direct connect- incorrect user unblock issue

packages/nulp_elite/src/components/EventCard.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
=> Task #0000 - event detail ui

packages/nulp_elite/src/components/FloatingChatIcon.js
=> Task #0000:chatbot ip changed

packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI fixes for carousel ui

packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI fixes for menu highligt, button size for popup, carousel text sizes

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/src/components/EventCard.js, packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #220889: UI implementation - Webinar List view

packages/nulp_elite/src/pages/SelectPreference.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #221247:on domain list page when click on any domain the page gets refresh and remain on the same page

packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/pages/FAQPage.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - Event detail mobile view , issue fixes

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/events/eventList.js
=> Resolve filter issue on contentList page

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/content/joinCourse.js
=> Task #0000: P1 bug fixes

packages/nulp_elite/src/pages/events/eventDetails.js
=> detail page

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI fixes

packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #0000: Bug fixes

packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> loader changes

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - Bug fixes

packages/nulp_elite/src/pages/events/eventList.js
=> Added filtrer in search API for showing latest created webinars first

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - ui fixes for content creator chat window

packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=>  detail page changes and loader for domain carusal

packages/nulp_elite/src/pages/events/eventList.js
=> gradelavel filter on eventList Page

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI fixes add chatbot icons and filter ui and footer color change for mobile

packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
=> event details changes

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
=> Detail page changes

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/content/noResultFound.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - add loader in domain list page

packages/nulp_elite/src/pages/events/eventDetails.js
=> detail page conditions

packages/nulp_elite/src/components/drawerFilter.js
=> clear all filters after clicking on the clear all button

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/events/eventList.js
=> Date Filter on eventList page

packages/nulp_elite/src/pages/search/ContentList.js
=> Resolve filter issue on contentList page (mobile view)

packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/SelectPreference.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/profile/certificate.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #0000:Bug fixes

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/components/CircularProgressWithLabel.js
=> Task #0000: Bug-Learning history expired status issue

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #0000: view all page delay result reflect and contentList reload blank page issue

package.json, packages/nulp_elite/src/pages/connections/chat.js
=> Task #0000: Emoticon functionality in direct connect

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/connections/chat.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #222006:[FE] Add predefined reasons for user block features(add dropdown)

packages/nulp_elite/src/styles/style.css
=> Card alignment fix for profile pages

packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js
=> Pagination on continueLearning and learningHistory Page

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/connections/chat.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
=> Task #0000: After connecting,user getting default invitation message and event detail on reload blank  issue

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/events/eventList.js
=> Search Filter on eventList Page

packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
Reverts NIUANULP/nulp-elite-ui#313
=> Revert "Task #0000:Bug fixes" - authentication issue

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
=> event API issue

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/search/ContentList.js
=> Task #222207:Bug fixes--Course detail page and cards button for sub-domain

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/events/eventList.js
=> Filter Chnages in eventList page

packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/registration/Otp.js, packages/nulp_elite/src/pages/registration/Registration.js
=> Task #0000: Registration routing

packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js
=> No result found integration on content page and view all page

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/styles/style.css, packages/players/quml/theme.css, packages/players/video/styles.css
=> Task #0000 -  bug fixes

packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI bug fixes

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI for event dashboard

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI for Player

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/events/dashboard.js
=> Task #0000:Dashboard API Integration

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI for dasboard time filter and bug fixes

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI enhancement

packages/nulp_elite/src/pages/events/dashboard.js
=> Task #0000: commented dynamic routing

package.json, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/events/dashboard.js
=> Task #0000:Dashboard report API Integration

packages/nulp_elite/src/pages/events/eventDetails.js
=> private event register button and register form

packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/events/eventDetails.js
=> event deatil redirect issue, private msg, player breadcrunb

packages/nulp_elite/src/pages/events/eventDetails.js
=>  attend button issue

package.json, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/votingDetails.js, packages/nulp_elite/src/pages/voting/votingList.js
=> Task #0000:Polls API integration

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/FAQPage.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - Domain-carousel changes

packages/nulp_elite/src/pages/profile/Profile.js
=> TASK : #0000 change user preferance popup functionality on profile page

packages/nulp_elite/src/pages/FAQPage.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/votingDetails.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI changes ekta

packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/drawerFilter.js
=> Task : #0000 Bug fixes

packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/styles/style.css
=> Fixed footer overlap issue, Voting dashboard

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/styles/style.css
=> Task #000 UI fixes, voting dasboard minor fixes

packages/nulp_elite/src/components/header.js
=> small ui fixes - header

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/ta/translation.json, packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #0000: Resolved filter  issue

packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/voting/createForm.js
=> Task #0000 - UI fixes for hide dummy grph event dashboard

packages/nulp_elite/src/components/VotingCard.js, packages/nulp_elite/src/components/VotingDrawerFilter.js, packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/votingDetails.js, packages/nulp_elite/src/pages/voting/votingList.js
=> Task #0000:Polls filter

packages/nulp_elite/src/components/EventCard.js, packages/nulp_elite/src/components/VotingCard.js, packages/nulp_elite/src/components/VotingDrawerFilter.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/votingDetails.js, packages/nulp_elite/src/pages/voting/votingList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI fixes for voting list, voting result, create form

packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task : #0000 Add Breadcrumbs on playerPage

packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/pages/voting/votingDashboard.js
=> Rendered api data on piechart

packages/nulp_elite/src/App.js, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/pages/voting/votingList.js
=> Task #0000:poll update

packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - UI fix for routing config for poll

packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/votingDashboard.js
=> Task #0000:fix t issue in polls

packages/nulp_elite/src/pages/voting/createForm.js
=> Added by default 2 options when creating a poll

packages/nulp_elite/src/pages/voting/votingDashboard.js
=> Added message if there is no records available for live,draft and closed polls

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/events/dashboard.js
=> TASK : #0000 subdomain filter

packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/pages/voting/votingList.js
=> Task #0000:orgname and roles add ed on profile and polls changes

packages/nulp_elite/src/pages/Loader.js, packages/nulp_elite/src/pages/Unauthorized.js, packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/pages/voting/votingDetails.js
=> Task #0000: Unauthorised page

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/noResultFound.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/styles/style.css
=> No Result found should set center allign, header language tooltip issue resolved

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/styles/style.css
=> Redesign create form page

packages/nulp_elite/src/assets/domainImgForm.json, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/noResultFound.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - Image update for domain carousel, domain carousel alignmet, no result found, notification popup hide

packages/nulp_elite/src/pages/events/dashboard.js
=> dashboard graph changes

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/noResultFound.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - no result found UI, domain carousel, notification

packages/nulp_elite/src/pages/SelectPreference.js
=> TASK : hardcoded preferance lable

packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - changes button color of event detail registration popup, player alignment fixes

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
=> enrollment list integration

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/components/VotingCard.js, packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/pages/voting/votingDetails.js
=> Task #0000:polls bug fixes

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/events/eventDetails.js
=> Task #0000:commented dev hardcoded url

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/profile/Profile.js
=> Task #0000:Bug fixes-organization name on profile, join course issue

packages/nulp_elite/src/components/VotingCard.js
=> Task #0000:multiple Tags on card

packages/nulp_elite/src/pages/content/Player.js
=> removed conflicts Player issue

packages/nulp_elite/src/pages/content/joinCourse.js
=> TASK : #0000 Start Learning and Continue Learning Functionality

packages/nulp_elite/src/components/VotingCard.js, packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/pages/voting/votingDashboard.js
=> Task #0000:Keywords button issue fixed

packages/nulp_elite/src/components/FeedbackPopup.js, packages/nulp_elite/src/pages/content/Player.js
=> TASK : #0000 Open FeedBack Form after completing content consumtion

packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/pages/voting/votingDetails.js
=> Task #0000:Updated Auto poll published

packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
=> Enrolment list API Issue

packages/nulp_elite/src/pages/events/dashboard.js
=> Task #0000- UI fix for event dahboard graph label

packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/pages/voting/votingList.js
=> Task #0000: Date filter polls

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/search/ContentList.js
=> TASK :#0000 Show subdomains on drawer filter as per Selected Domain

packages/nulp_elite/src/assets/eventRecording.json, packages/nulp_elite/src/pages/events/eventDetails.js
=> TASK : #0000 Event Recording API integration

packages/nulp_elite/src/components/FeedbackPopup.js, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/events/eventDetails.js
=> TASK : #0000 Integrate Feedback API

packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/search/DomainList.js
=> minor bugs

packages/nulp_elite/src/pages/events/eventDetails.js
=> update chaneg for event img

packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js
=> Task #0000:Roles mapped with name

packages/nulp_elite/src/components/header.js
=> Tooltip for language is missing

packages/nulp_elite/src/components/FloatingChatIcon.js, packages/nulp_elite/src/pages/content/Player.js
=> Task #0000:Added chatbot and player URL

packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/events/eventDetails.js
=> TASK : #0000Recording popup -Adding API connection to UI

packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/pages/voting/votingDashboard.js
=> Task #224882 - [FE] - To add delete confirmation modal on draft polls delete button

packages/nulp_elite/src/pages/content/joinCourse.js
=> TASK : #0000 Restrict user to access unenrolled course contents

packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/Card.js, packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profileData.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Task #0000 - Carousel Closes After Selecting Domain on Home Page,Breadcrumb Alignment Issues Across All Pages

packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/styles/style.css
=> create poll UI issues

packages/nulp_elite/src/components/drawerFilter.js, packages/nulp_elite/src/pages/search/ContentList.js
=> TASK :#0000 Filters not working properly on contentList page

packages/nulp_elite/src/pages/SelectPreference.js
=> TASK : #0000 don't show cancel button on preferance popup

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/ta/translation.json, packages/nulp_elite/public/locales/te/translation.json, packages/nulp_elite/src/pages/FAQPage.js
=> Bug #225050 -  FAQ language selection Not Reflecting for other than english language

packages/nulp_elite/src/pages/events/eventDetails.js
=> events details page changes

packages/nulp_elite/src/components/VotingCard.js
=> Task #0000: isMobile undefined issue fixed

packages/nulp_elite/src/pages/content/Player.js
=> Bug #225226 - [dev] content tags alignment should be at left side on content detail page.

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/ta/translation.json, packages/nulp_elite/public/locales/te/translation.json, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/styles/style.css
=> Task #225311 - [FE] - content player detail page changes

packages/nulp_elite/src/pages/events/eventDetails.js
=> TASK : #0000 Enrollment-list API integration changes

packages/nulp_elite/src/pages/voting/votingDashboard.js
=> Bug #224621 - Pie Chart Option Text Not Fully Visible

packages/nulp_elite/src/pages/content/joinCourse.js
=> TASK : #0000 changed consumerId from user orgId to course orgId for consent form update

packages/nulp_elite/src/components/VotingDrawerFilter.js, packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/styles/style.css
=> Bug #225319 - filter by and clear All button allignment are not proper on poll list page

packages/nulp_elite/src/pages/voting/votingDetails.js
=> Bug #224623 - Calendar Icon and Voting Icon Not Properly Aligned on Poll Details Page

packages/nulp_elite/src/pages/voting/createForm.js
=> Bug #225049 - select user dropdown with seacrh is not working in create poll form

package.json, packages/common-lib/src/components/SunbirdPlayer.js, packages/nulp_elite/src/pages/content/Player.js
=> TASK : # 0000 Assesment Tracking and merit Certificate flow

packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js
=> TASK : #0000 Chenged se_boards to board on category page

packages/nulp_elite/src/pages/SelectPreference.js, packages/nulp_elite/src/pages/content/Player.js
=> TASK : Preferance popup changes and certificate issue resolved

packages/nulp_elite/src/components/drawerFilter.js
=> TASK : drawer filter issue resolved

packages/nulp_elite/src/pages/profile/Profile.js
=> Bug #225395 - When selecting designation with long text user id not display properly

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/events/eventDetails.js
=> TASK : #0000 Attend Weinar functionality for private event

packages/nulp_elite/src/pages/content/Player.js
=> Feedback #225691 - In description,it isshowing content name.it should show content description

packages/nulp_elite/src/pages/content/joinCourse.js
…it should open the content detail page.
=> Bug #225389 - on course detail page,clicking anywhere on the content it should open the content detail page

packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/content/joinCourse.js
=> breadcrumb to back button on player page

packages/nulp_elite/src/styles/style.css
=> Bug #225390 - Hand cursor is missing on Add New Button and Back button on add connections page

packages/nulp_elite/src/pages/events/eventList.js
=> private event in enrollment list

packages/nulp_elite/src/pages/events/eventDetails.js
=> unable to enroll to public event

packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/styles/style.css
=> Bug #225399 - Inconsistenet card size on poll dashboard

packages/nulp_elite/src/pages/profile/learningHistory.js
=> Bug #225396 - On learning history page,'No result found' message is left alligned.

packages/nulp_elite/src/pages/voting/votingList.js
=> Task #0000: Poll page list issue fixed

packages/nulp_elite/src/pages/events/dashboard.js
=> Bug #225739 - [Webapp] On hovering top trending events graph,unable to see the full event name.

packages/nulp_elite/src/pages/content/joinCourse.js
=> cert mesg changes

packages/nulp_elite/src/components/Notification.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/configs/urlConfig.json
=> TASK : #225942 Show Default notifications to user

packages/nulp_elite/src/components/FloatingChatIcon.js, packages/nulp_elite/src/styles/style.css
…e after hover on the icon' on all pages
=> Feedback #226011 - Nulp Assist must be visible small 'Text should come after hover on the icon' on all pages

packages/nulp_elite/public/locales/en/translation.json
=> Bug #226005 - [Webapp] Make Faq word in capital letters on the footer and in help page

packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/events/eventList.js
=> TASK : #0000 show only public events on all event page

packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/styles/style.css
=> Bug #225930 - Inconsistent Button Positions on Poll Cards for Polls With and Without Keywords

packages/nulp_elite/src/pages/events/eventList.js
=> TASK : #0000 Pagination on my events tab

packages/nulp_elite/src/styles/style.css
=> Bug #226015 - All messages in the chat box are right aligned. They should be left aligned

packages/nulp_elite/src/pages/voting/createForm.js
…in description form of Poll Creation.[keep minimum 10 words]
=> Feedback #226368 - [webapp] There is a need to remove the word limit in description form of Poll Creation.[keep minimum 10 words]

packages/nulp_elite/src/styles/style.css
=> Feedback #226377 - [webapp] Move position of chatbot to the footer blue patti

packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/pages/voting/votingDashboard.js
=> dev deployment issue

packages/nulp_elite/src/components/Card.js
=> Bug #226453 - App icon is not visible on certain courses

packages/nulp_elite/src/pages/voting/createForm.js
…in description form of Poll Creation.[keep minimum 10 words] and maximum 1000 letters
=> Feedback #226368 - [webapp] There is a need to remove the word limit, set minimum 10 and maximum 1000 characters

packages/nulp_elite/src/pages/search/DomainList.js
=> TASK :#0000 remove content and Quiz / Test from recently added contents

packages/nulp_elite/src/pages/connections/chat.js, packages/nulp_elite/src/pages/content/joinCourse.js
=> Bug #226505 - Remove close icon on chat window(it should only show on chat with creator popup)

packages/nulp_elite/src/pages/profile/Profile.js
=> Bug #225511 - Mobile- Edit Icon on Profile Page Appearing Outside Profile Detail Area

packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js
=> TASK :#0000 Open popup for copyright after clicking on credits

packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/search/ContentList.js
=> TASK : #0000 Data Fluctuation issue on contentList page

packages/nulp_elite/src/pages/search/ContentList.js
=> TASK : #0000 Removed setCurrentPage before calling fetchData

packages/nulp_elite/src/pages/search/ContentList.js
=> TASK : #0000 Setcurrent page to 1 before aplying filter

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/ta/translation.json, packages/nulp_elite/public/locales/te/translation.json, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> TASK :#0000 UI Chnages for domain selection and credits

packages/nulp_elite/src/pages/content/joinCourse.js
=> TASK : #0000 Changes in other information on course detail page

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/ta/translation.json, packages/nulp_elite/public/locales/te/translation.json, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/styles/style.css
=> Merging dev into prod I

packages/nulp_elite/src/components/domainCarousel.js, packages/nulp_elite/src/styles/style.css
=> Task #226646 - [FE]- Redesign Domain Bar

packages/nulp_elite/src/pages/voting/createForm.js, packages/nulp_elite/src/styles/style.css
=> Bug #226607 - [webapp] Language constatns are missing on create poll page - only for prod

packages/nulp_elite/src/pages/events/eventDetails.js
=> TASK :#0000 event registration button validation changes

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/styles/style.css
…e background color for search textbox
=> Feedback #226744 - [webapp] When user on the search page just add some background color for search textbox.

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/ta/translation.json, packages/nulp_elite/public/locales/te/translation.json, packages/nulp_elite/src/pages/content/joinCourse.js
=> TASK : #0000 Credit Popup Showing more values check conditions

packages/nulp_elite/src/pages/connections/chat.js, packages/nulp_elite/src/pages/events/eventDetails.js
=> TASK :#0000 Resolved event is live still showing ended message.please check and Unable to send more than 700 char

packages/nulp_elite/src/pages/profile/Profile.js
=> Bug #226189 - When roles are more than two UI for profile page distorted

package.json
=> [FE]-package.json after installing react-ga library for google analytics

packages/nulp_elite/src/pages/SelectPreference.js
=> TASK : #0000 Comment Topic from the User preferance popup

packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/styles/style.css
…ser on this tags [Role on profile page] [PFA]
=> Bug #226704 - [Content Detail Page, profile page] Showing the handcurser on this tags [Role on profile page] [PFA]

packages/nulp_elite/src/pages/content/joinCourse.js
=> complete messege

packages/nulp_elite/src/pages/content/joinCourse.js
Reverts NIUANULP/nulp-elite-ui#635
=> Revert "complete messege"

packages/nulp_elite/src/pages/content/CategoryPage.js
=> TASK:#0000 Clear domain changes on category page

packages/nulp_elite/src/pages/content/joinCourse.js
=>  cert no found

packages/nulp_elite/src/pages/content/joinCourse.js
=>  course detail not loading

packages/nulp_elite/src/components/EventCard.js, packages/nulp_elite/src/styles/style.css
…ine,Bug #227343-[webapp => event] Allignments are not proper on event card
=> Bug #227091 - [mobile - content page] Button lable should be in one line, Bug #227343 - [webapp => event] Allignments are not proper on event card

packages/nulp_elite/src/components/EventCard.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/voting/votingDashboard.js
=> Bug #227342 - [Desktop => course detail page] Back button is missing on course detail page

packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/events/eventDetails.js
=> TASK : #0000 Changed Keywords for eventOrganisedBy and IssueCerificate

packages/nulp_elite/src/pages/voting/votingList.js
=> Bug #224665 - Date filter is not working on poll list page

packages/nulp_elite/src/pages/voting/votingList.js
=> Bug #227764 : Date filter is not working on poll list page

packages/nulp_elite/src/styles/style.css
=> Bug #225510 - mobile- Subdomain Selection: Long Text Not Fully Visible in Preferences Popup

packages/nulp_elite/src/App.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> commiting create component basic

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> learnathon content form

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/events/eventDetails.js
=> TASK : #0000 Event crtificate functionality

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/eventDetails.js
=> update learnathon branch

packages/nulp_elite/src/components/learnathon/LernModal.js, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Task #228134 - [FE] - Registration side changes for learnathon (webapp)-updated channel name

packages/nulp_elite/src/pages/content/joinCourse.js
=> disable join button for creator

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/events/eventDetails.js, packages/nulp_elite/src/pages/voting/pollsDetails.js, packages/nulp_elite/src/pages/voting/votingDashboard.js, packages/nulp_elite/src/styles/style.css
=> Task #227193  - [FE] - Mobile responsive

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/content/joinCourse.js
=> join course issue

packages/nulp_elite/src/App.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> learnathon crete form changes

packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> list and form learnathon

packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> deployment issues

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/events/eventDetails.js
Reverts NIUANULP/nulp-elite-ui#664
=> Revert "TASK : #0000 Event crtificate functionality"

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> learnathon form

packages/nulp_elite/src/components/VotingDrawerFilter.js, packages/nulp_elite/src/pages/FAQPage.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/content/AllContent.js, packages/nulp_elite/src/pages/content/CategoryPage.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/content/pdf.js, packages/nulp_elite/src/pages/events/dashboard.js, packages/nulp_elite/src/pages/events/eventList.js, packages/nulp_elite/src/pages/profile/certificate.js, packages/nulp_elite/src/pages/search/ContentList.js, packages/nulp_elite/src/pages/search/DomainList.js, packages/nulp_elite/src/pages/voting/pollsDetails.js
=> Resolved sticky footer issue

packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/styles/style.css
=> Bug #227994 - [webapp] Footer is misalligned on some of the pages. PFA

packages/nulp_elite/src/configs/urlConfig.json
=> urlconfig changes

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js, packages/nulp_elite/src/styles/style.css
=> Task #228043 - learnathon - create contnet form UI changes

packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/styles/style.css
=> Task #228044 - learnathon creator- my content list view(UI changes)

packages/nulp_elite/src/App.js, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/events/eventList.js
=> Resolved deployment issue

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/te/translation.json, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/learnathon/lernVotingList.js, packages/nulp_elite/src/pages/voting/votingDetails.js
=> TASK #228992 : Votting List and Learnathon Votting flow

packages/nulp_elite/src/pages/content/joinCourse.js
=> Bug #228501  -[webapp - course detail page] course module structure UI is not looking well. PFA

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/ta/translation.json, packages/nulp_elite/public/locales/te/translation.json
=> Bug : #0000 Resolved language constant issue

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/ta/translation.json, packages/nulp_elite/public/locales/te/translation.json, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> Learnathon

scripts/pack-prod-build.sh
=> learnathon review

packages/nulp_elite/public/index.html, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js, packages/nulp_elite/src/pages/learnathon/lernReviewerList.js
=> learn deployment

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> creation changes - open personal form

packages/nulp_elite/src/components/learnathon/LernModal.js
=> TASK #0000 : Provide creator access changes

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> creation changes

packages/nulp_elite/public/locales/be/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/gg/translation.json, packages/nulp_elite/public/locales/hi/translation.json, packages/nulp_elite/public/locales/ma/translation.json, packages/nulp_elite/public/locales/mal/translation.json, packages/nulp_elite/public/locales/ta/translation.json, packages/nulp_elite/public/locales/te/translation.json, packages/nulp_elite/src/pages/content/Player.js
=> TASK #0000 : Add Learnathon Details on content Detail page

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> upload content

package.json, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js, yarn.lock
=> extra fields and poll creation

packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> terms and conditions

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> TASK : #00000 Make indicative themes and indicative subthemes dynamic

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> commiting preview

packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/learnathon/lernVotingList.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Bug #0000 : Navigation to mylernsubmissions page

packages/nulp_elite/src/pages/content/Player.js
=> TASK : #0000 Provide content_id to poll create API

packages/nulp_elite/src/pages/content/Player.js
=> Learnathon - demo updates

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> form apdate- tnc and user name

packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/pages/learnathon/lernVotingList.js
…p) with updated figma UI and funtionality
=> Task #228528 -[FE] - Registration side changes for learnathon (webapp) with updated figma UI and funtionality

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> youtube and name description validation

packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js, packages/nulp_elite/src/pages/learnathon/lernReviewerList.js
=> delete, youtube, pegination

packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js, packages/nulp_elite/src/pages/learnathon/lernReviewerList.js, packages/nulp_elite/src/pages/learnathon/lernVotingList.js
=> pegination and redirection

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> TASK : #0000 resolved indicative_subthmes value not geeting displayed

packages/nulp_elite/src/pages/voting/votingDetails.js
=> Bug #229317 : Poll detail page - Back button issue

packages/nulp_elite/src/pages/profile/certificate.js
Reverts NIUANULP/nulp-elite-ui#685
=> Revert "Revert "Task #228396 : [FE] Add the Ribbon on certificate card of course and …""

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> changes for validation

packages/nulp_elite/src/pages/connections/chat.js
=> Update chat.js - For production deployment (chat with creator)

packages/nulp_elite/src/configs/routeConfig.json
=> delete, youtube

packages/nulp_elite/src/components/ExportToCSV.js, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/LearnathonDashboard.js
=> hide workspace and show dashboard

packages/nulp_elite/src/components/header.js
=> learn workspace menu

packages/nulp_elite/src/pages/content/Player.js
=> learn update

packages/nulp_elite/src/pages/LearnathonDashboard.js, packages/nulp_elite/src/pages/content/Player.js
=> Back button view on dashboard

packages/common-lib/src/components/SunbirdPlayer.js, packages/nulp_elite/src/pages/content/Player.js, packages/players/quml/demoData.js
=> merit certificate is not working 

packages/nulp_elite/src/pages/content/Player.js
=> adding changes for merit certificate

packages/nulp_elite/src/pages/LearnathonDashboard.js
=> Bug #230580 - [Learnathon Dashboard ] "Export to CSV" Button Sticks to State Filter. PFA

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/LearnathonDashboard.js, packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/search/DomainList.js
=> dashboard updates

packages/nulp_elite/src/components/Footer.js, packages/nulp_elite/src/pages/LearnathonDashboard.js, packages/nulp_elite/src/pages/content/Player.js
=> Learnathon changes

packages/nulp_elite/src/components/learnathon/LernModal.js, packages/nulp_elite/src/pages/content/Player.js
=> publish date change

packages/nulp_elite/src/components/learnathon/LernModal.js, packages/nulp_elite/src/pages/search/DomainList.js
=> TASK #0000 : Comment conditional rendering of buttons for demo

packages/nulp_elite/src/components/learnathon/LernModal.js, packages/nulp_elite/src/pages/search/DomainList.js
=> learn module redirection

packages/nulp_elite/src/pages/content/Player.js
=> TASK #00000 : Content Player page is getting blank

packages/nulp_elite/src/components/learnathon/LernModal.js, packages/nulp_elite/src/pages/search/DomainList.js
=> toaster mesg for new user

packages/nulp_elite/src/components/learnathon/LernModal.js
=> deployment bug

packages/nulp_elite/src/pages/search/DomainList.js
=> TASK #00000 :   Change button colours on learnathon banner

packages/nulp_elite/src/pages/search/DomainList.js
=> TASK #00000 : Add Validation to learnathon banner

packages/nulp_elite/src/pages/search/DomainList.js
=> build issue

packages/nulp_elite/src/pages/content/Player.js
=> TASK  #00000 :Change Votting start Date to actual votting start date

packages/nulp_elite/src/pages/content/Player.js
=> TASK #00000 : Removed hardcoded votting end date

packages/nulp_elite/public/locales/as/translation.json, packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/public/locales/kn/translation.json, packages/nulp_elite/public/locales/or/translation.json, packages/nulp_elite/public/locales/pa/translation.json, packages/nulp_elite/public/locales/ur/translation.json, packages/nulp_elite/src/pages/FAQPage.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> New changes prod

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/components/learnathon/LernModal.js, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js, packages/nulp_elite/src/pages/search/ContentList.js
=> Bug fix prod

packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> Bux fixing

packages/nulp_elite/src/pages/learnathon/learnCities.json, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> cities drop down is corrected

packages/nulp_elite/src/components/header.js
=> Workspace link in dropdown when login

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/joinCourse.js
=> Bux fixing- Workspace link coming  in dropdown for Profile

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> Bug-  Miscellaneous/ Others removed from learnathon create form and workspace link in dropdown section

packages/nulp_elite/public/locales/en/translation.json, packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/content/joinCourse.js, packages/nulp_elite/src/pages/learnathon/LearnathonDashboard.js
=> Learnathon Link added in profile dropdown and mobile number column added in learn dashboard page

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/learnathon/LearnathonDashboard.js
=> The Learnathon link  added under the Dashboard section in the Profile dropdown.

packages/nulp_elite/src/components/header.js, packages/nulp_elite/src/pages/learnathon/learnCities.json, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> City drop down changed, learnathon link added in dashboard section , miscellanious remove from learn create form

packages/nulp_elite/src/components/header.js
=> org admin added in roles

packages/nulp_elite/public/locales/en/translation.json
=> Translation for LEARTHANON added

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> Validation for Sub theme in learn create form added

packages/nulp_elite/src/components/learnathon/LernModal.js, packages/nulp_elite/src/pages/search/DomainList.js
=> learnthon review date

packages/nulp_elite/src/pages/search/DomainList.js
=> reviewer changes

packages/nulp_elite/src/App.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/learnathon/LearnathonDashboard.js, packages/nulp_elite/src/pages/learnathon/UserList.js
=> learnathon participants list page

packages/nulp_elite/src/pages/learnathon/UserList.js
=> removed name in code

packages/nulp_elite/src/components/drawerFilter.js
=> Hidden Sub domain in content list page

packages/nulp_elite/src/components/drawerFilter.js
=> Subdomain prod

packages/nulp_elite/src/pages/learnathon/UserList.js
=> Elite fixing

packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js
=> TASK #00000 : Add new states

packages/nulp_elite/src/pages/learnathon/UserList.js
=> name is updated

packages/nulp_elite/src/pages/learnathon/LernSubmissionTable.js, packages/nulp_elite/src/pages/learnathon/lernCreatorForm.js, packages/nulp_elite/src/pages/search/DomainList.js
=> Learnathon date prod

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/learnathon/UserList.js
=> api endpoint changed in user list page

packages/nulp_elite/src/configs/urlConfig.json, packages/nulp_elite/src/pages/learnathon/UserList.js
=> Learnathon dev date

packages/nulp_elite/src/pages/learnathon/UserList.js
=> request body for passing changed in api

packages/nulp_elite/src/pages/learnathon/UserList.js
=> remove extra request in request body

packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/learnathon/lernVotingList.js
=> [FE] - To display Voting list categorywise

package.json, packages/nulp_elite/src/components/Forum.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profile/continueLearning.js, packages/nulp_elite/src/pages/profile/learningHistory.js
=> Task #239632 : [FE] Learner is able to see My post and My activity in the discussion forum on the profile page

packages/nulp_elite/src/pages/profile/MyActivity.js, packages/nulp_elite/src/pages/profile/MyPosts.js, packages/nulp_elite/src/pages/profile/Profile.js
=> Task #239632 feat: [FE] Learner is able to see My post and My activity in the discussion forum on the profile page

packages/nulp_elite/public/index.html
=> Customer Request #239575 feat: Need to add Microsoft Clarity code on all pages of NULP

packages/nulp_elite/src/components/header.js
=> Task #239872: [FE] When logout from learner App also logout in discussion forum

packages/nulp_elite/src/components/header.js
=> Task #239872: [FE] When logout from learner App also logout in discussion forum-1

packages/nulp_elite/src/components/header.js
=> Task #239872: [FE] Cookie clear approach

packages/nulp_elite/src/pages/profile/MyActivity.js, packages/nulp_elite/src/pages/profile/MyPosts.js, packages/nulp_elite/src/pages/profile/Profile.js
=> Task #239925: [FE] Integrate My activity in profile page

packages/nulp_elite/public/index.html, packages/nulp_elite/src/pages/learnathon/LearnathonDashboard.js
=> Customer Request #240054 feat: API exposing phone number and email of Learnathon User on content view page

packages/nulp_elite/public/index.html, packages/nulp_elite/src/pages/learnathon/LearnathonDashboard.js
=> Customer Request #240054 feat: API exposing phone number and email of Learnathon User on content view page 

packages/nulp_elite/public/index.html, packages/nulp_elite/src/pages/learnathon/LearnathonDashboard.js
=> Prod Deployment on 2nd May 2025

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js, packages/nulp_elite/src/pages/profile/MyPosts.js, packages/nulp_elite/src/pages/search/ContentList.js
=> Task #240434: [FE] When click on connect with author open chat on portal

packages/nulp_elite/src/pages/profile/MyActivity.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/search/ContentList.js
=> Task #239632:Minor bug fixes

packages/nulp_elite/src/components/Footer.js
=> Task #239632:Mobile view discussion forum re-direction

packages/nulp_elite/src/pages/SelectPreference.js, packages/nulp_elite/src/pages/profile/Profile.js
Country selects box needs to be added on registration page
Added Country dropdown with India and Others options.
Select the country. If country is selected as india. state and district dropdown will appear. if country is selcted as Ohers Other Country input box will appear
=> Customer Request #240251 Feat country field in update profile

package.json, packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/CourseStructuredData.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/pages/content/AllPublicContent.js, packages/nulp_elite/src/pages/content/joinCourse.js
=> Task #240606: New Approach-Implement structured Google Search Central schema on all pages, contents and d

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/content/AllPublicContent.js
=> Task #0000: location and designation saved in cookie for DF

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js
=> Task #0000: Closing chat after sending

packages/nulp_elite/src/App.js
Customer Request #1003 
Added logic to check if country state and district fields is null or not
added code to check if country state and district fields is null or not in app.js
login via user who has not country state and district added in their profile
=> Customer Request #240790 fix: profile pop for country state and district

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js
Reverts NIUANULP/nulp-elite-ui#1022
=> Revert "Task #0000: Closing chat after sending"

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/profileData.js
Customer Request #240790
Update Profile Popup – Add Country Dropdown & Auto-Prompt for Missing Location Details
changes in profileData.js for ountry Dropdown
login with user no having country state and district fields. popup should come to fill these fields.
=> Customer Request #240790 fix: Update Profile Popup – Add Country Dropdown & Auto-Prompt for Missing Location Details

packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/content/joinCourse.js
=> Customer Request - Bug #241239 fix: Merit Certificate Not Issued for Some Users

packages/nulp_elite/src/App.js, packages/nulp_elite/src/pages/profile/Profile.js, packages/nulp_elite/src/pages/profileData.js
Fixed logic for not pupulating the fields like organisation, bio, designtion, usertype state and district
Removed the unused api call and added fetch userinfo api to get all the userdata and populate it
Login from old user who has not added country, state and district in their profile. Popup should come to update these fields.
=> Customer Request #240790 fix: Add Country Dropdown & Auto-Prompt for Missing Location Details

packages/nulp_elite/src/pages/connections/chat.js
=> Task #0000: add redirection after chat sent first time

packages/nulp_elite/src/pages/content/Player.js, packages/nulp_elite/src/pages/search/ContentList.js
=> Customer Request #239057 - Search on Player Page Redirects to Blank Page

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js
=> Task #0000: connect with author issue fixed for discussion forum

package.json, packages/nulp_elite/package.json, packages/nulp_elite/src/App.js, packages/nulp_elite/src/components/CourseStructuredData.js, packages/nulp_elite/src/configs/routeConfig.json, packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js, packages/nulp_elite/src/pages/content/AllPublicContent.js, packages/nulp_elite/src/pages/content/joinCourse.js, scripts/pack-prod-build.sh
=> Customer Request #0000:Public page search and central google search

packages/nulp_elite/src/pages/connections/AddConnections.js
=> Task #0000:Chat is not opening for some users

packages/nulp_elite/src/pages/connections/AddConnections.js, packages/nulp_elite/src/pages/connections/chat.js
=> Task #0000:Refactoring chat and addconnections pages
